--- 
title: "R, Rstudio, and ggplot2"
author: "Sunbok Lee"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "This is an introduction to R, Rstudio, and ggplot2"
---

# R 

## Why R? 
* R is a **free** open source software.
* R is a language designed especially for **statistical analysis**. Many statistical methods are first implemented in R. 
* R provides many tools for publication-quality **data visualization** (e.g., `ggplot2`).
* R provides many tools for **data processing (or data wrangling)** (e.g., `dplyr`, `tidyr`). Data come from diverse sources these days (e.g., microarray, EEG, fMRI, eyetrackers, facebook, twitter, many sensors, ... ).
    * e.g., JSON is a popular file format for data exchange: [https://en.wikipedia.org/wiki/JSON](https://en.wikipedia.org/wiki/JSON)
    * e.g., Biometric research: [IMotions](https://imotions.com/?creative=287840870074&keyword=imotions&matchtype=p&network=g&device=c&gclid=EAIaIQobChMI3pas5oOO5AIVlBx9Ch28hwboEAAYASAAEgJlUfD_BwE)

## Installing R

* You can download and install **a base distribution and packages (base R)** from the official R webiste: [https://www.r-project.org](https://www.r-project.org).

* About 14,000 packages **extend** the base R. R packages are **collections of functions and data sets** developed by the R community. They increase the power of R by improving existing base R functionalities. A list of R packages are available here:[https://cran.r-project.org/web/packages/available_packages_by_name.html](https://cran.r-project.org/web/packages/available_packages_by_name.html)

## Installing RStudio

* RStudio is an **integrated development environment (IDE)** for R. 

* You can download and install the RStudio from the RStudio website: [https://www.rstudio.com](https://www.rstudio.com). 

* A short tour to the RStudio IDE: [https://www.rstudio.com/products/rstudio/](https://www.rstudio.com/products/rstudio/). 

## Cheat Sheets for R

* RStudio provides cheat sheets for R: [https://www.rstudio.com/resources/cheatsheets/](https://www.rstudio.com/resources/cheatsheets/). 

## Rmarkdown files

* Rmarkdown files for this materials can be downloaded here: [https://github.com/sunboklee/PSYC6300](https://github.com/sunboklee/PSYC6300)

## R topics covered in this course

* Base R
* tidyverse 
    * The `tidyverse` package was developed for more efficient data science in R. In the `tidyverse` package, the `dplyr`, `tidyr`, `ggplot2`, and `purrr` packages provide many useful functions for efficient data transformation, data tidying, data visualization, and iteration, respectively.
    * Useful free R books: [https://bookdown.org](https://bookdown.org). R for Data Science [@Wickham] is a useful resource for the `tidyverse` package. 
  
  

